apiVersion: apps/v1
kind: Deployment
metadata:
  name: business-clock-api
  namespace: company
spec:
  replicas: 3
  selector:
    matchLabels:
      app: business-clock-api
  template:
    metadata:
      labels:
        app: business-clock-api
    spec:
      containers:
      - name: business-clock-api
        image: jeffrygonzalez/business-clock-api-aug-2023:sha-cf164eb
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        env:
          - name: TZ
            value: "America/New_York"
          - name: ASPNETCORE_ENVIRONMENT
            value: Development
        ports:
        - containerPort: 80
